device: cuda
seed: 1002

# distributed settings
rounds: 500
total_users: 100
user_num: 50
part_rate: 0.5
user_data_mapping: "data/fmnist/user_dataidx_map_0.10.dat"

# compressor
compressor: "randomsparse"
A: 0.005
B: 0.5
# hyperparameters and settings
aggregator: "mean"
unbiased_indicator: True
batch_size: 128
local_epochs: 1
optimizer: "SGD"
momentum: 0
nesterov: False
lr: 1.
weight_decay: 1.e-5
global_lr: 0.1
global_lr_init: 0.1
mc: 5

# DP settings
epsilon: 1
delta: 1.e-5
clipping_scheme: "by_norm"
clipping_bound: 2.5
add_noise: True
noise_multiplier: 1

model: "DenseNN"
checkpoint_path: ""

# Simulation dataset configurations
dataset: "fmnist"
data_path: "./data/fmnist/"

# Log configurations
output_folder: "experiments"
test_interval: 1
print_every:   20
log_level:   "INFO"
log_file:    "./train.log"
