device: cuda
seed: 1002

# distributed settings
rounds: 1
total_users: 50
user_num: 50
user_data_mapping: "data/cifar10/50user_dataidx_map2_1.00.dat"

# compressor
# compressor: "randomsparse"
# A: 0.005
# B: 0.5
compressor: "none"

# hyperparameters and settings
aggregator: "mean"
unbiased_indicator: True
batch_size: 128
local_epochs: 100
optimizer: "SGD"
momentum: 0.9
nesterov: True
lr: 1.e-1
weight_decay: 1.e-5
global_lr: 1
global_lr_init: 0.1
mc: 5

# DP settings
dp_on: False
# dp_on: True
epsilon: 1
delta: 1.e-5
clipping_scheme: "by_norm"
clipping_bound: 2
add_noise: True
noise_multiplier: 1

model: "resnet50_gn"
checkpoint_path: "modelzoo/resnet50/resnet50_gn.pth"
pretrained: True

# Simulation dataset configurations
dataset: "cifar10_224"
data_path: "./data/cifar10/"
pytorch_builtin: True

# Log configurations
output_folder: "experiments"
test_interval: 1
print_every:   20
log_level:   "INFO"
log_file:    "./train.log"
