device: cuda
seed: 1002

# distributed settings
rounds: 1000
total_users: 31
part_rate: 1
user_data_mapping: "data/fmnist/user_dataidx_map_0.50.dat"

# compressor
compressor: "signSGD"

# hyperparameters and settings
aggregator: "vote"
batch_size: 32
local_epochs: 1
optimizer: "SGD"
momentum: 0
nesterov: False
lr: 5.e-4
weight_decay: 5.e-4
global_lr: 1.e-3
mc: 1

# DP settings
epsilon: 100
delta: 1.e-5
# max_grad_norm: 1.0
clipping_scheme: "by_norm"
clipping_bound: 100.
add_noise: False
noise_multiplier: 1.


model: "lenet"
checkpoint_path: ""

# Simulation dataset configurations
dataset: "fmnist"
data_path: "./data/fmnist/"

# Log configurations
output_folder: "experiments"
test_interval: 1
print_every:   20
log_level:   "INFO"
log_file:    "./train.log"
