device: cuda
seed: 1002

# distributed settings
rounds: 500
total_users: 100
user_num: 50
part_rate: 0.3
user_data_mapping: "data/mnist/user_dataidx_map_0.10.dat"

# compressor
compressor: "ternary"
attacker_compressor: "attacker_ternary"
A: 0.005
B: 0.05
optimal_config: True
sparse_ratio: 0.01
mu_target: 0.5

# hyperparameters and settings
aggregator: "vote"
unbiased_indicator: False
batch_size: 128
local_epochs: 1
optimizer: "SGD"
momentum: 0
nesterov: False
lr: 1
weight_decay: 1.e-5
global_lr: 0.001
global_lr_init: 0.001
mc: 3

# DP settings
epsilon: 100
delta: 1.e-5
# max_grad_norm: 1.0
clipping_scheme: "by_value"
clipping_bound: 0.0003
add_noise: False
noise_multiplier: 1.

model: "DenseNN"
checkpoint_path: ""

# Simulation dataset configurations
dataset: "mnist"
data_path: "./data/mnist/"

# Log configurations
output_folder: "experiments"
test_interval: 1
print_every:   20
log_level:   "INFO"
log_file:    "./train.log"
